// This file is part of wbaxterh/vouched.
// Portions derived from midnightntwrk/example-bboard.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the vouched verified-purchase reviews
 * CLI. The entry point is the run function, at the end of the file.
 * We expect the startup files (standalone.ts, preprod.ts, etc.) to call
 * run with a configuration that sets the network addresses of the
 * servers this file relies on.
 *
 * The demo flow this CLI walks through:
 *   buy  -> the buyer derives a commitment locally (the store never sees
 *           the secret) and the store records it on-chain
 *   review -> the buyer proves membership of the purchase tree in zero
 *           knowledge; the review lands on-chain keyed by a nullifier
 *           that nothing links back to the purchase commitment
 *   review again -> the same nullifier is rejected, so one purchase
 *           gets exactly one review
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import {
  VouchedAPI,
  type VouchedDerivedState,
  vouchedPrivateStateKey,
  type VouchedProviders,
  type VouchedCircuitKeys,
  type DeployedVouchedContract,
  type PrivateStateId,
  productIdFromName,
} from '../../api/src/index';
import { type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { ledger, type Ledger } from '../../contract/src/managed/vouched/contract/index.js';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { assertIsContractAddress, toHex } from '@midnight-ntwrk/midnight-js-utils';
import { TestEnvironment } from '@midnight-ntwrk/testkit-js';
import { MidnightWalletProvider } from './midnight-wallet-provider';
import { randomBytes } from '../../api/src/utils';
import { unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { syncWallet, waitForUnshieldedFunds } from './wallet-utils';
import { generateDust } from './generate-dust';
import { VouchedPrivateState } from '../../contract/src/witnesses.js';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * productNameFromId: inverse of productIdFromName for display purposes.
 * Product ids are UTF-8 names zero-padded to 32 bytes, so strip the
 * padding and decode.
 */

const productNameFromId = (id: Uint8Array): string => {
  let end = id.length;
  while (end > 0 && id[end - 1] === 0) {
    end -= 1;
  }
  return new TextDecoder().decode(id.slice(0, end));
};

/* **********************************************************************
 * getVouchedLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific vouched contract. Note that
 * the Ledger type returned here is not some generic, abstract ledger
 * object, but specifically the type generated by the Compact compiler
 * to correspond to the ledger declaration in the vouched contract.
 */

export const getVouchedLedgerState = async (
  providers: VouchedProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new vouched store contract
  2. Join an existing vouched store contract
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (providers: VouchedProviders, rli: Interface, logger: Logger): Promise<VouchedAPI | null> => {
  let api: VouchedAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        api = await VouchedAPI.deploy(providers, logger);
        logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        return api;
      case '2':
        api = await VouchedAPI.join(providers, await rli.question('What is the contract address (in hex)? '), logger);
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * buyProduct: the checkout moment. The buyer derives the purchase
 * commitment locally from their secret (an off-chain pure-circuit
 * evaluation, no proof involved), and only that opaque commitment is
 * recorded on-chain by the store.
 */

const buyProduct = async (vouchedApi: VouchedAPI, rli: Interface, logger: Logger): Promise<void> => {
  const name = await rli.question('Which product are you buying? ');
  const productId = productIdFromName(name);
  const commitment = await vouchedApi.commitmentFor(productId);
  logger.info(`Buyer derived purchase commitment locally: ${toHex(commitment)}`);
  logger.info('(the store receives only this value; the buyer secret never leaves the wallet)');
  await vouchedApi.recordPurchase(commitment);
  logger.info(`Purchase of '${name}' recorded on-chain.`);
};

/* **********************************************************************
 * postReview: the payoff. The buyer proves in zero knowledge that some
 * commitment in the purchase tree belongs to them and matches this
 * product, without revealing which one. The review is keyed by a
 * nullifier, so a second review from the same purchase is rejected by
 * the contract.
 */

const postReview = async (vouchedApi: VouchedAPI, rli: Interface, logger: Logger): Promise<void> => {
  const name = await rli.question('Which product are you reviewing? ');
  const ratingText = await rli.question('Rating (1-5)? ');
  const text = await rli.question('Review text? ');
  const rating = BigInt(ratingText);
  logger.info('Generating zero-knowledge proof of purchase (this takes a moment)...');
  await vouchedApi.postReview(productIdFromName(name), rating, text);
  logger.info(`Review of '${name}' posted.`);
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the public ledger state. This is the "what
 * the chain sees" view: opaque purchase commitments on one side,
 * nullifier-keyed reviews on the other, and nothing linking the two.
 */

const displayLedgerState = async (
  providers: VouchedProviders,
  deployedVouchedContract: DeployedVouchedContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedVouchedContract.deployTxData.public.contractAddress;
  const ledgerState = await getVouchedLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no vouched contract deployed at ${contractAddress}`);
  } else {
    logger.info(`== Public ledger state (visible to anyone) ==`);
    logger.info(`Purchase commitments recorded: ${ledgerState.purchases.firstFree()}`);
    logger.info(`Reviews posted: ${ledgerState.reviewCount}`);
    for (const [nullifier, text] of ledgerState.reviewTexts) {
      const product = productNameFromId(ledgerState.reviewProducts.lookup(nullifier));
      const rating = ledgerState.reviewRatings.lookup(nullifier);
      logger.info(`  review[${toHex(nullifier).slice(0, 8)}..] product='${product}' rating=${rating} text='${text}'`);
    }
    logger.info(`(no field links a review to a purchase commitment or a wallet)`);
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the purchase
 * secret held by this DApp instance.
 */

const displayPrivateState = async (providers: VouchedProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get(vouchedPrivateStateKey);
  if (privateState === null) {
    logger.info(`There is no existing vouched private state`);
  } else {
    logger.info(`Current purchase secret is: ${toHex(privateState.purchaseSecret)}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the derived state, which combines the
 * ledger state with private state into the shape a storefront UI would
 * render: counts plus the assembled review list.
 */

const displayDerivedState = (derivedState: VouchedDerivedState | undefined, logger: Logger) => {
  if (derivedState === undefined) {
    logger.info(`No vouched state currently available`);
  } else {
    logger.info(`Purchases recorded: ${derivedState.purchaseCount}`);
    logger.info(`Reviews posted: ${derivedState.reviewCount}`);
    for (const review of derivedState.reviews) {
      const stars = '*'.repeat(Number(review.rating));
      logger.info(`  [${stars}] '${review.text}' (product ${review.productId.slice(0, 16)}...)`);
    }
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the vouched CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Buy a product (record a verified purchase)
  2. Post a review (requires a verified purchase of that product)
  3. Display the public ledger state (known by everyone)
  4. Display the current private state (known only to this DApp instance)
  5. Display the current derived state (known only to this DApp instance)
  6. Exit
Which would you like to do? `;

const mainLoop = async (providers: VouchedProviders, rli: Interface, logger: Logger): Promise<void> => {
  const vouchedApi = await deployOrJoin(providers, rli, logger);
  if (vouchedApi === null) {
    return;
  }
  let currentState: VouchedDerivedState | undefined;
  const stateObserver = {
    next: (state: VouchedDerivedState) => (currentState = state),
  };
  const subscription = vouchedApi.state$.subscribe(stateObserver);
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      try {
        switch (choice) {
          case '1':
            await buyProduct(vouchedApi, rli, logger);
            break;
          case '2':
            await postReview(vouchedApi, rli, logger);
            break;
          case '3':
            await displayLedgerState(providers, vouchedApi.deployedContract, logger);
            break;
          case '4':
            await displayPrivateState(providers, logger);
            break;
          case '5':
            displayDerivedState(currentState, logger);
            break;
          case '6':
            logger.info('Exiting...');
            return;
          default:
            logger.error(`Invalid choice: ${choice}`);
        }
      } catch (e) {
        logError(logger, e);
        logger.info('Returning to main menu...');
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<string | undefined> => {
  if (config instanceof StandaloneConfig) {
    return GENESIS_MINT_WALLET_SEED;
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return toHex(randomBytes(32));
      case '2':
        return await rli.question('Enter your wallet seed: ');
      case '3':
        logger.info('Exiting...');
        return undefined;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * run: the main entry point that starts the whole vouched CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, testEnv: TestEnvironment, logger: Logger): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  const providersToBeStopped: MidnightWalletProvider[] = [];
  try {
    const envConfiguration = await testEnv.start();
    logger.info(`Environment started with configuration: ${JSON.stringify(envConfiguration)}`);
    const seed = await buildWallet(config, rli, logger);
    if (seed === undefined) {
      return;
    }
    const walletProvider = await MidnightWalletProvider.build(logger, envConfiguration, seed);
    providersToBeStopped.push(walletProvider);
    const walletFacade: WalletFacade = walletProvider.wallet;

    await walletProvider.start();

    const unshieldedState = await waitForUnshieldedFunds(logger, walletFacade, envConfiguration, unshieldedToken());
    const nightBalance = unshieldedState.balances[unshieldedToken().raw];
    if (nightBalance === undefined) {
      logger.info('No funds received, exiting...');
      return;
    }
    logger.info(`Your NIGHT wallet balance is: ${nightBalance}`);

    if (config.generateDust) {
      const dustGeneration = await generateDust(logger, seed, unshieldedState, walletFacade);
      if (dustGeneration) {
        logger.info(`Submitted dust generation registration transaction: ${dustGeneration}`);
        await syncWallet(logger, walletFacade);
      }
    }

    const zkConfigProvider = new NodeZkConfigProvider<VouchedCircuitKeys>(config.zkConfigPath);
    const providers: VouchedProviders = {
      privateStateProvider: levelPrivateStateProvider<PrivateStateId, VouchedPrivateState>({
        privateStateStoreName: config.privateStateStoreName,
        signingKeyStoreName: `${config.privateStateStoreName}-signing-keys`,
        privateStoragePasswordProvider: () => {
          return 'Vouched-Test-2026!';
        },
        accountId: seed,
      }),
      publicDataProvider: indexerPublicDataProvider(envConfiguration.indexer, envConfiguration.indexerWS),
      zkConfigProvider: zkConfigProvider,
      proofProvider: httpClientProofProvider(envConfiguration.proofServer, zkConfigProvider),
      walletProvider: walletProvider,
      midnightProvider: walletProvider,
    };
    await mainLoop(providers, rli, logger);
  } catch (e) {
    logError(logger, e);
    logger.info('Exiting...');
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        for (const wallet of providersToBeStopped) {
          logger.info('Stopping wallet...');
          await wallet.stop();
        }
        if (testEnv) {
          logger.info('Stopping test environment...');
          await testEnv.shutdown();
        }
      } catch (e) {
        logError(logger, e);
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}
