name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  #v7.0.0

      - name: Setup Compact Compiler
        uses: midnightntwrk/setup-compact-action@836895c8fffbbea6bd986af2b17e8941ff29d1f8
        with:
          compact-version: '0.31.1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  #v7.0.0
        with:
          node-version: "24"

      # A bug in npm optional dependencies fails the build, which is fixed in npm 11 or later
      # but the setup-node action isn't using a newer version of npm yet
      # See https://github.com/npm/cli/issues/4828
      - name: Update NPM
        run: |
          npm install -g npm@latest
          npm --version

      # We use --legacy-peer-deps because as of v3.4.1 vite-plugin-wasm doesn't play well with vite 7
      # So this allows them to be installed regardless; They *have* implemented support, they just haven't published a release yet
      # https://github.com/Menci/vite-plugin-wasm/pull/73
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Compile and test contract
        working-directory: contract
        run: |
          npm run ci

      - name: api
        working-directory: api
        run: |
          npm run ci

      - name: Compile bboard-cli
        working-directory: bboard-cli
        run: |
          npm run ci

      - name: Compile bboard-ui
        working-directory: bboard-ui
        run: |
          npm run ci
